  language: python
python:
  - "3.5"
sudo: required
branches:
  only:
  - sources
env:
  global:
    secure: eP8/Quj4bMjCxax6569o6/vVm27yOXFhNUEXIK2W4ETDIa/zl74nUBGGFB6mzos2MphNK04e0buyHMqevVSCktrb87ENBXtFrj7mc7MZKOv3BkvTy2/Te+ka3EBBvVExbS1/szPlMJmEJBeDdeto16uqKPRwNPbimAg//ZoS6HN2G/PQGe9mSJGkiFfE82ACX/eo8bCYzu8OlyqW3he7z1xnzoiGRvDgEGJ2I1LFdPF64IGop+2MVWZjDegCfcQsiJL1nzhP7k5wn/Qff4LrqazQqgXtregpvcqu+vtm18mq6y7ve4wQZ43oHjuXD0zGG4hjhd94RoAisH0647NH4PcbdTE79NZzXVzGuZV0tA9dCgA/pZ0X9RHf4IAuN7G2Css+O8+SA9D07ysC2QZO5XnjNGmkl8GJEFQDyhuNsuPwEwIFOR/141LwH/FMDovi+/yzD6oEXMCpK/jwyKWiqrio0WXdwN1Uqk9cCbpgVc8ypSE5PW21doyOR5d/Q49ssDhWd5LaVAUEwSMLibbr+lxu71RArbiX99ysTrmDYMQpHSAl5YBCh9EmGi/9ZoyfHbv0QSUhSLTPgTvy/ac4NP0ZXUNlbA1iXBiSx3tz7bWISUaZasJhoYck3QTqtCBBDO70jBSZxbazIjfW2fm6ohfzi2kUHyhqIpCVQyhcVTI=

install:
- pip install ghp-import
- git clone https://github.com/getpelican/pelican-plugins
script:
- make publish github